# DOWNLINK — Drone → Ground
PKT_TELEMETRY       = "TEL"
PKT_FIRE_EVENT      = "FIRE"
PKT_IMAGE_START     = "IMG_START"
PKT_IMAGE_DATA      = "IMG"
PKT_IMAGE_END       = "IMG_END"
PKT_MISSION_ACK     = "MISSION_ACK"
PKT_MISSION_NACK    = "MISSION_NACK"
PKT_CMD_RESPONSE    = "CMD_RESP"

# UPLINK — Ground → Drone
PKT_ARM             = "ARM"
PKT_DISARM          = "DISARM"
PKT_MODE            = "MODE"
PKT_MISSION_UPLOAD  = "MISSION"
PKT_MISSION_START   = "MISSION_START"
PKT_MISSION_CLEAR   = "MISSION_CLEAR"

# ACK / NACK — Bidirectional
PKT_ACK_FIRE        = "ACK_FIRE"
PKT_ACK_IMG         = "ACK_IMG"
PKT_NACK_IMG        = "NACK_IMG"

# PRIORITY LEVELS (lower number = higher priority)
PRIORITY_ACK        = 1
PRIORITY_TELEMETRY  = 2
PRIORITY_CMD_RESP   = 3
PRIORITY_FIRE       = 4
PRIORITY_MISSION    = 5
PRIORITY_IMAGE      = 6
